#version: '3.8'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.8.0
    container_name: food-elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - "9200:9200"
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
    networks:
      - food-network

  food-service:
    build: .
    container_name: food-semantic-service
    ports:
      - "3030:3030"  # Fuseki
      - "8080:8080"  # Web API
    volumes:
      - ./images:/app/data/images
      - ./WebSemantics.rdf:/app/data/ontology/WebSemantics.rdf
      - ./food_mappings.json:/app/data/food_mappings.json
    depends_on:
      - elasticsearch
    networks:
      - food-network

networks:
  food-network:
    driver: bridge

volumes:
  elasticsearch_data:
    driver: local